### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by ldkong1205** [jiazhou-garland/EventBind#1]
Hi @jiazhou-garland, thanks for sharing this work!

I would like to know when will the code be publicly available, thanks.

**Comment by jiazhou-garland** [comment]
Sorry, the code and checkpoint will be publicly available as soon as possible after the paper acception. Thank you for you attention.

**Comment by jiazhou-garland** [comment]
Hi Lindong Kong，

Thank you for your attention to this paper.

We will release the codes and pre-trained weights on GitHub (
https://github.com/jiazhou-garland/E-CLIP) after the paper acceptance ASAP.

Best,

Jiazhou Zhou

Lingdong Kong ***@***.***> 于2023年9月8日周五 19:44写道：

**Comment by ldkong1205** [comment]
Thanks for your reply. Looking forward to your code!

**Comment by jiazhou-garland** [comment]
All codes and checkpoints have been released. If you find my repositories useful, please consider staring 🌟 it and citing 📑 the corresponding papers.
