### ISSUE TITLE
About extract event

### ISSUE THREAD

**Issue by HyunsuYEE** [jiazhou-garland/EventBind#2]
hello. it's wonderful works! 
in the paper, there is event retrieval by using the img or text query.
<img width="852" alt="image" src="https://github.com/user-attachments/assets/3c49d34e-0421-4b26-8c79-473bef360d04">

can you inform "how to retrieval the event from other modality query"?
thank you.

**Comment by jiazhou-garland** [comment]
For image-to-event retrieval, obtain the image query embedding and all event embeddings, then calculate the similarity of all image-event pairs. Finally, take the Topk highest similarity scores as the Topk retrieved results.

**Comment by jiazhou-garland** [comment]
Please refer to the evaluate function in the train_dp_datasetname.py for code implementation.

**Comment by HyunsuYEE** [comment]
thank you for your answering.
But, I want to know "how to visualize the events".
can you share the code for visualize it?

**Comment by jiazhou-garland** [comment]
For the visualization of events, you may refer to the data loader part, where codes related to transforming event to event frames are released.
