### ISSUE TITLE
How to train the model and what does the WIT dataset in the table refer to?

### ISSUE THREAD

**Issue by bollossom** [jiazhou-garland/EventBind#3]
How to train Event-Bind? Can I migrate the pre-trained weights of N-imagenet to other datasets?

**Comment by jiazhou-garland** [comment]
Hello, I have released the training and evluation codes. Please refer to the Quick Start.

WIT is the pertaining dataset of CLIP, which we employ as the backbone.

Of course you can migrate the pre-trained weights of N-Imagenet to other datasets, just change the checkpoint path in the config file.
