### ISSUE TITLE
Run problems

### ISSUE THREAD

**Issue by bollossom** [jiazhou-garland/EventBind#5]
excuseme, Is there a problem with the model input code?
Traceback (most recent call last):
  File "/EventBind/train_dp_N-Caltech101.py", line 444, in <module>
    main(cfg)
  File "/EventBind/train_dp_N-Caltech101.py", line 396, in main
    epoch_loss = train_one_epoch(EventCLIP, cfg, loss_scaler, optimizer, lr_sched, train_loader, epoch)
  File "/EventBind/train_dp_N-Caltech101.py", line 33, in train_one_epoch
    = model(events, images, labels, real_num_frame)

RuntimeError: forward() expected at most 3 argument(s) but received 5 argument(s). Declaration: forward(__torch__.multimodal.model.multimodal_transformer.Multimodal self, Tensor image, Tensor input) -> ((Tensor, Tensor))

**Comment by jiazhou-garland** [comment]
Hello, please provide your configuration information and full error information.

The error comes from the number of model inputs, which is defined in EventBind/model/EventCLIP.py line 47
>     def forward(self, events, image, class_idxs, real_num_frame):
It seems to be no problem for the original code which defined 5 inputs.

**Comment by bollossom** [comment]
EventCLIP.load_state_dict(torch.load(cfg['MODEL']['Load_Path'])) 
raise TypeError(f"Expected state_dict to be dict-like, got {type(state_dict)}.")
TypeError: Expected state_dict to be dict-like, got <class 'torch.jit._script.RecursiveScriptModule'>. 
After this error occurred, I changed the line 
EventCLIP.load_state_dict(torch.load(cfg['MODEL']['Load_Path']))  to 
EventCLIP = torch.jit.load(cfg['MODEL']['Load_Path']). 
Then the above input and model input did not match.

**Comment by bollossom** [comment]
I have solved the problem, thank you. Have a nice day!!!
