### ISSUE TITLE
DataLoader about N-Imagenet

### ISSUE THREAD

**Issue by Hotpottttt** [jiazhou-garland/EventBind#7]
hi, I've got some questions about the N-ImageNet in DataLoader which is seemed to be lack of N-imagenet_train&val.txt. Is it hided in some places? It would be grateful if u could answer this question.

**Comment by jiazhou-garland** [comment]
The size of .txt file for N-ImageNet is greater than 25MB, which is too large to upload on Github repository.

We follow the official train-val split of ImageNet/N-Imagenet, your may refer to it and create the .txt file on your own.

Kind note: Follow the same .txt format as other datasets which is available in their corresponding folders.

**Comment by Hotpottttt** [comment]
Thanks, it helps
